### PR TITLE
Update gemfile

### PR DESCRIPTION
**Pull request by ArturMinnullin**
Update a few gems due to new vulnerabilities.

screen shot 2015-06-17 at 13 22 25

### CODE REVIEW

**Comment by VladimirMikhailov** [comment]
:+1:

**Comment by dmitrytrager** [comment]
:gem: :ship:

**Comment by ArturMinnullin** [comment]
Unfortunately, I can't merge it by myself :disappointed:

**Comment by vast** [comment]
:heart:

**Comment by vast** [comment]
@ArturMinnullin, could you please also update [CHANGELOG](https://github.com/fs/rails-base/blob/master/CHANGELOG.md#unreleased)?

**Comment by ArturMinnullin** [comment]
@vast done

**Comment by vast** [comment]
@ArturMinnullin, it'd be great to specify why we upgraded these gems, something like:

> Update`rails`, `jquery-rails`, `rack`, `web-console`: security vulnerabilities, see http://weblog.rubyonrails.org/2015/6/16/Rails-3-2-22-4-1-11-and-4-2-2-have-been-released-and-more/

**Comment by vast** [comment]
@ArturMinnullin, awesome. Thanks!

**Pull request merged**
