### PR TITLE
Replace static pages with high_voltage

### PR DESCRIPTION
**Pull request by IlkhamGaysin**
Related to: https://github.com/fs/rails-base/issues/472

### CODE REVIEW

**Comment by IlkhamGaysin** [comment]
@timurvafin  Please review.

**Comment by timurvafin** [comment]
@IlkhamGaysin what is advantage of this gem over pure Rails `PagesController`? What is the reason to implement additional dependency in the application?

**Comment by IlkhamGaysin** [comment]
@timurvafin I guess hiding a controller which is the most of cases is only used to show the views.

**Comment by timurvafin** [comment]
I don't think we need this extra dependency.

**Pull request closed without merging**
