### PR TITLE
WIP: Introduce deadweight for tracking unused css selectors

### PR DESCRIPTION
**Pull request by dmitrytrager**
This PR is created according to #225 

Added Rack middleware is based on that described in [this article](https://robots.thoughtbot.com/use-deadweight-and-your-integration-suite-to). Although I don't see any reason to insert it exactly after Rack::Lock.

This PR inserts [Deadweight](https://github.com/aanand/deadweight) as a last step of bin/quality script. It also precompiles assets in test env since we need to provide compiled css for deadweight.

Main drawback here is following:
- this solution looks for css used in response data
- response data is collected as a result of requests to application
- requests are triggered by tests
- as a result, current tests can provide not all the possible responses from the app and we can treat some selectors as 'unused' mistakenly

### CODE REVIEW

**Comment by timurvafin** [comment]
@dmitrytrager I believe you need involve @maratfakhreev or @rustemginiyatullin to review this PR.

**Comment by dmitrytrager** [comment]
@timurvafin that's for sure. I just think that time did not come yet)

**Comment by maratfakhreev** [comment]
@dmitrytrager looks awesome) Could you show how this awesome tool works? Tomorrow for example.

**Comment by timurvafin** [comment]
@dmitrytrager what's the status? Please reopen when it will be updated.

**Pull request closed without merging**
