### PR TITLE
Update ruby and rails

### PR DESCRIPTION
**Pull request by ruslankhaertdinov**

### CODE REVIEW

**Comment by ArturMinnullin** [comment]
`ruby 2.3` is already been [released](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released). Perhaps It makes sense to update it immediately?

**Comment by ruslankhaertdinov** [comment]
@ArturMinnullin I don't mind :+1:

**Comment by timurvafin** [comment]
@ruslankhaertdinov https://semaphoreci.com/docs/languages/ruby/switching-ruby-version-on-specific-branch.html

**Comment by ruslankhaertdinov** [comment]
@timurvafin thanks

**Comment by ruslankhaertdinov** [comment]
@ArturMinnullin  I suggest to wait until `2.4.0` will become available through `rbenv` (seems like only `2.4.0-dev` available for now)

**Comment by ruslankhaertdinov** [comment]
@ArturMinnullin sorry, no problems, I'll update ruby up to 2.3.0

**Comment by ruslankhaertdinov** [comment]
@ArturMinnullin @timurvafin 
`ruby 2.3.0` not supported by Semaphoreci for now. Supported stack - semaphore 2016-01-05 16-14-57:
supported stack - semaphore 2016-01-05 16-14-57

**Comment by ruslankhaertdinov** [comment]
@timurvafin done

**Pull request merged**
