### PR TITLE
Add text version for devise mailer views

### PR DESCRIPTION
**Pull request by IlkhamGaysin**

### CODE REVIEW

**Comment by timurvafin** [comment]
@IlkhamGaysin thank you for PR. What is the reason to use slim for text templates?

**Comment by IlkhamGaysin** [comment]
@timurvafin I think, for all of us familiar syntax and in rails base we use this templater for views.

**Comment by timurvafin** [comment]
@IlkhamGaysin please review how email looks in the plain/text version. Currently it without line breaks.

You could not use `\n\r` with slim b/c it designed for HTML.
Please try to use `text.erb` instead.

**Comment by IlkhamGaysin** [comment]
@timurvafin Yeah, replaced with erb format.

**Pull request merged**
