### PR TITLE
Disable simple form i18n lookup for hints and placeholders by default

### PR DESCRIPTION
**Pull request by ArthurZaharov**
Related to: #313

### CODE REVIEW

**Comment by timurvafin** [comment]
@ArthurZaharov could you please provide flamegraph from rack-profiler before and after these changes?

**Comment by ArthurZaharov** [comment]
@timurvafin this is flamegraph for /users/sign_in page.

Before:
image

After:
image

**Comment by ArthurZaharov** [comment]
@timurvafin Please don't merge it yet. Need to squash commits.

**Comment by ArthurZaharov** [comment]
@timurvafin done. Please review it again.

**Comment by timurvafin** [comment]
To review related issue https://github.com/plataformatec/simple_form/issues/1227

**Comment by timurvafin** [comment]
@ArthurZaharov based on recent research could you please upgrade simple form in different PR?

**Comment by ArthurZaharov** [comment]
@timurvafin Yes, sure.

**Comment by timurvafin** [comment]
Closed if favor of https://github.com/fs/rails-base/pull/400

**Pull request closed without merging**
