### PR TITLE
[#325] Authentication via social networks (with schema)

### PR DESCRIPTION
**Pull request by ruslankhaertdinov**
Related to: https://github.com/fs/rails-base/issues/325

-
Schema:
omniauth scheme

### CODE REVIEW

**Comment by ruslankhaertdinov** [comment]
@maximlarionov please take a look again ;)

**Comment by maximlarionov** [comment]
@ruslankhaertdinov seems everything is :ok: for me, good job on this :+1:

**Comment by IldusSadykov** [comment]
:+1:

**Comment by timurvafin** [comment]
Moved to https://github.com/fs/rails-base-examples/pull/3

**Pull request closed without merging**
