### PR TITLE
Show slowest specs through "profile_examples" option

### PR DESCRIPTION
**Pull request by ruslankhaertdinov**
Show slowest 10 specs (with path and consumed time)
Read more about [profile_examples](https://www.relishapp.com/rspec/rspec-core/docs/configuration/profile-examples) option

### CODE REVIEW

**Comment by ArturMinnullin** [comment]
:+1:

**Comment by timurvafin** [comment]
@ruslankhaertdinov may it's better to set `--profile` in `.rspec` file?

**Comment by ruslankhaertdinov** [comment]
@timurvafin locally it (`--profile`) works fine and I think it should also be good on CI.

**Comment by timurvafin** [comment]
@ruslankhaertdinov looks ok, please cleanup commits and we are ready to merge!

**Comment by ruslankhaertdinov** [comment]
@timurvafin done

**Pull request merged**
