### PR TITLE
Add policy object

### PR DESCRIPTION
**Pull request by timurvafin**

### CODE REVIEW

**Comment by ArturMinnullin** [comment]
@timurvafin May be we shouldn't add application_policy? Because pundit has default generator and it creates application_policy that differs.

**Comment by timurvafin** [comment]
@ArturMinnullin I've removed things related to `scope` from `ApplicationPolicy` b/c think it gives us not very good behavior.

**Comment by ArturMinnullin** [comment]
:ok:

**Comment by dmitrytrager** [comment]
:ok:

**Pull request merged**
