### PR TITLE
Replace Pundit with ActionPolicy

### LINKED ISSUE #606: Introduce ActionPolicy gem

### PR DESCRIPTION
**Pull request by DmitryBarskov**
# Summary

Resolves #606.

# Review notes

While reviewing pull-request (especially when it's your pull-request),
please make sure that:

- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduces DB fields have indexes and constraints
- routes are RESTful, no useless routes
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes

# Deploy notes

Notes regarding deployment the contained body of work.
These should note any db migrations, ENV variables, services, etc.

### CODE REVIEW

**Comment by DmitryBarskov** [comment]
Should we use `verify_authorized`?

**Comment by EvgeniyEsaulkov** [comment]
> Should we use `verify_authorized`?

I think we don't need it right now because we haven't many places where we use `authorize!` (actually I didn't found any :-) ). So we can add it in the future if needed.

**Review by EvgeniyEsaulkov — CHANGES_REQUESTED** [review]
Can you please update `README.md` too?

**Comment by DmitryBarskov** [comment]
> I think we don't need it right now

Makes sense

**Review by ArthurZaharov — APPROVED** [review]

**Pull request merged**
