### PR TITLE
Prepare devise for cutomization

### PR DESCRIPTION
**Pull request by timurvafin**
* set devise `scoped_views` to true and move views to `app/views/users/`
* mailer views moved from `devise/mailer` to user_mailer
* custom mailer will allow us to wrap `@resource` with presenter to use in the mailer views

### CODE REVIEW

**Comment by dmitrytrager** [comment]
:ok:

**Comment by timurvafin** [comment]
@vast any thoughts here?

**Comment by vast** [comment]
@timurvafin, :ok: with the current changes. What's next?

**Comment by timurvafin** [comment]
@vast not sure about custom devise controllers
* `app/controllers/users/sessions_controllers`
* `app/controllers/users/registrations_controllers`

**Pull request merged**
