### PR TITLE
Update Formulaic gem

### PR DESCRIPTION
**Pull request by KirillKayumov**
Update formulaic gem to the latest version for new features, such a ```fill_form_and_submit``` for example.

### CODE REVIEW

**Comment by timurvafin** [comment]
@KirillKayumov could we try to use this new method in the specs?

**Comment by KirillKayumov** [comment]
@timurvafin I think yes

**Comment by KirillKayumov** [comment]
@timurvafin there are 2 moments about this new method:
1. It tries to find submit button's name in locale file.
2. It uses ```click_on (alias of click_link_or_button)``` method to click on submit button in form, so it means that if page contains any link and submit button in form with the same names, form likely won't be submitted.
Please check the last commit.

**Comment by timurvafin** [comment]
@KirillKayumov looks like you are trying to solve here two things: gem update and submit helper translation.

I've created separate issues related to the submit helper https://github.com/fs/rails-base/issues/258. Let's see what we will get there and after that move with this pull request.

**Comment by timurvafin** [comment]
@KirillKayumov https://github.com/fs/rails-base/pull/259 merged. Could you please update your pull request accordingly?

**Comment by KirillKayumov** [comment]
@timurvafin done

**Comment by timurvafin** [comment]
@KirillKayumov could you please squash commits before closing pull request.

**Comment by KirillKayumov** [comment]
@timurvafin done, please check

**Pull request merged**
