### PR TITLE
Add slim-lint

### PR DESCRIPTION
**Pull request by vast**
Finally we can force double quotes even in `.slim` templates

/cc @timurvafin

### CODE REVIEW

**Comment by timurvafin** [comment]
@vast it will be great to find way how to determine single quotes in the pure slim strings
For example, here `html class='no-js' lang="en"` will be no errors from slim-lint.

**Comment by vast** [comment]
@timurvafin, I don't see anything similar in "slim-lint" linters. Probably we can make our own, let me investigate it.

**Comment by timurvafin** [comment]
@vast any updates here?

**Comment by vast** [comment]
@timurvafin, there is no simple way to teach `slim_lint` to catch inconsistent quotes in its syntax because it works in terms of atoms (tag, attribute, interpolation) and simply ignores quotes in its grammar.

See:

* https://github.com/sds/slim-lint/blob/master/lib/slim_lint/linter/tag_case.rb
* https://github.com/sds/slim-lint/blob/master/lib/slim_lint/atom.rb

**Comment by timurvafin** [comment]
@vast ok, let's merge as is

**Pull request merged**
