### PR TITLE
Add Gaffe to handle Rails error pages in a clean, simple way

### PR DESCRIPTION
**Pull request by timurvafin**
* https://github.com/mirego/gaffe
* Closes https://github.com/fs/rails-base/issues/296

сс @dmitrytrager @vast @VladimirMikhailov

### CODE REVIEW

**Comment by arkadiybutermanov** [comment]
:ok:

**Comment by vast** [comment]
:-1: that doesn't look right to me. Have a look at what we got on AR::NotFound in production environment:

screen shot 2015-08-19 at 16 42 35

Also this gem doesn't cover situation with 50x errors when backend (Rails) is dead.

@timurvafin, could you please clarify what exactly we want to customize and compile from app views?

**Comment by timurvafin** [comment]
@vast 

1. Error page design -- agreed need to put more love here and hide internal staff.
2. In case Rails backend is dead `public/500.html` should be displayed by upfront server (nginx on Heroku?)

General idea is to let developer to customize 404 pages (`AR::NotFound` exceptions`) and other internal Rails error. Custom page should look and feel like other pages of the application, so we should have access to the partials, assets, route helpers, etc.

**Comment by timurvafin** [comment]
@rustemginiyatullin could you please help here to customize error pages?

You need to create
* `app/views/layouts/error.html.slim`
* `app/views/errors/not_found.html.slim`
* `app/views/errors/internal_server_error.html.slim`

**Comment by timurvafin** [comment]
Should be moved to https://github.com/fs/rails-base-examples

**Pull request closed without merging**
